CREATE UNIQUE NONCLUSTERED INDEX IX_Pack_Name ON dbo.Pack
	(
		Name DESC
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]



