//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TZero_ConfigModel", "FK_Connection_connectionState", "ConnectionStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ZeroConfiguration.Entities.ConnectionStatu), "Connection", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ZeroConfiguration.Entities.Connection), true)]
[assembly: EdmRelationshipAttribute("TZero_ConfigModel", "FK_Connection_Terminal", "Terminal", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ZeroConfiguration.Entities.Terminal), "Connection", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ZeroConfiguration.Entities.Connection), true)]
[assembly: EdmRelationshipAttribute("TZero_ConfigModel", "FK_TerminalProperty_Terminal", "Terminal", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ZeroConfiguration.Entities.Terminal), "TerminalProperty", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ZeroConfiguration.Entities.TerminalProperty), true)]
[assembly: EdmRelationshipAttribute("TZero_ConfigModel", "Terminal_Module", "Module", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ZeroConfiguration.Entities.Module), "Terminal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ZeroConfiguration.Entities.Terminal))]

#endregion

namespace ZeroConfiguration.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Connection> Connections
        {
            get
            {
                if ((_Connections == null))
                {
                    _Connections = base.CreateObjectSet<Connection>("Connections");
                }
                return _Connections;
            }
        }
        private ObjectSet<Connection> _Connections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConnectionStatu> ConnectionStatus
        {
            get
            {
                if ((_ConnectionStatus == null))
                {
                    _ConnectionStatus = base.CreateObjectSet<ConnectionStatu>("ConnectionStatus");
                }
                return _ConnectionStatus;
            }
        }
        private ObjectSet<ConnectionStatu> _ConnectionStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Module> Modules
        {
            get
            {
                if ((_Modules == null))
                {
                    _Modules = base.CreateObjectSet<Module>("Modules");
                }
                return _Modules;
            }
        }
        private ObjectSet<Module> _Modules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SystemProperty> SystemProperties
        {
            get
            {
                if ((_SystemProperties == null))
                {
                    _SystemProperties = base.CreateObjectSet<SystemProperty>("SystemProperties");
                }
                return _SystemProperties;
            }
        }
        private ObjectSet<SystemProperty> _SystemProperties;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Terminal> Terminals
        {
            get
            {
                if ((_Terminals == null))
                {
                    _Terminals = base.CreateObjectSet<Terminal>("Terminals");
                }
                return _Terminals;
            }
        }
        private ObjectSet<Terminal> _Terminals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TerminalProperty> TerminalProperties
        {
            get
            {
                if ((_TerminalProperties == null))
                {
                    _TerminalProperties = base.CreateObjectSet<TerminalProperty>("TerminalProperties");
                }
                return _TerminalProperties;
            }
        }
        private ObjectSet<TerminalProperty> _TerminalProperties;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Connections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConnections(Connection connection)
        {
            base.AddObject("Connections", connection);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConnectionStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConnectionStatus(ConnectionStatu connectionStatu)
        {
            base.AddObject("ConnectionStatus", connectionStatu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModules(Module module)
        {
            base.AddObject("Modules", module);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SystemProperties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSystemProperties(SystemProperty systemProperty)
        {
            base.AddObject("SystemProperties", systemProperty);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Terminals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTerminals(Terminal terminal)
        {
            base.AddObject("Terminals", terminal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TerminalProperties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTerminalProperties(TerminalProperty terminalProperty)
        {
            base.AddObject("TerminalProperties", terminalProperty);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="terminalCode">No Metadata Documentation available.</param>
        public int GetPacksToSend(Nullable<global::System.Int32> terminalCode)
        {
            ObjectParameter terminalCodeParameter;
            if (terminalCode.HasValue)
            {
                terminalCodeParameter = new ObjectParameter("TerminalCode", terminalCode);
            }
            else
            {
                terminalCodeParameter = new ObjectParameter("TerminalCode", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("GetPacksToSend", terminalCodeParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TZero_ConfigModel", Name="Connection")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Connection : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Connection object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="terminalCode">Initial value of the TerminalCode property.</param>
        /// <param name="stamp">Initial value of the Stamp property.</param>
        public static Connection CreateConnection(global::System.String code, global::System.Int32 terminalCode, global::System.DateTime stamp)
        {
            Connection connection = new Connection();
            connection.Code = code;
            connection.TerminalCode = terminalCode;
            connection.Stamp = stamp;
            return connection;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TerminalCode
        {
            get
            {
                return _TerminalCode;
            }
            set
            {
                OnTerminalCodeChanging(value);
                ReportPropertyChanging("TerminalCode");
                _TerminalCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TerminalCode");
                OnTerminalCodeChanged();
            }
        }
        private global::System.Int32 _TerminalCode;
        partial void OnTerminalCodeChanging(global::System.Int32 value);
        partial void OnTerminalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Stamp
        {
            get
            {
                return _Stamp;
            }
            set
            {
                OnStampChanging(value);
                ReportPropertyChanging("Stamp");
                _Stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stamp");
                OnStampChanged();
            }
        }
        private global::System.DateTime _Stamp;
        partial void OnStampChanging(global::System.DateTime value);
        partial void OnStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StatusCode
        {
            get
            {
                return _StatusCode;
            }
            set
            {
                OnStatusCodeChanging(value);
                ReportPropertyChanging("StatusCode");
                _StatusCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusCode");
                OnStatusCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _StatusCode;
        partial void OnStatusCodeChanging(Nullable<global::System.Int32> value);
        partial void OnStatusCodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_ConfigModel", "FK_Connection_connectionState", "ConnectionStatus")]
        public ConnectionStatu ConnectionStatu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConnectionStatu>("TZero_ConfigModel.FK_Connection_connectionState", "ConnectionStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConnectionStatu>("TZero_ConfigModel.FK_Connection_connectionState", "ConnectionStatus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ConnectionStatu> ConnectionStatuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ConnectionStatu>("TZero_ConfigModel.FK_Connection_connectionState", "ConnectionStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ConnectionStatu>("TZero_ConfigModel.FK_Connection_connectionState", "ConnectionStatus", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_ConfigModel", "FK_Connection_Terminal", "Terminal")]
        public Terminal Terminal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Terminal>("TZero_ConfigModel.FK_Connection_Terminal", "Terminal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Terminal>("TZero_ConfigModel.FK_Connection_Terminal", "Terminal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Terminal> TerminalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Terminal>("TZero_ConfigModel.FK_Connection_Terminal", "Terminal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Terminal>("TZero_ConfigModel.FK_Connection_Terminal", "Terminal", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TZero_ConfigModel", Name="ConnectionStatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConnectionStatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConnectionStatu object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        public static ConnectionStatu CreateConnectionStatu(global::System.Int32 code)
        {
            ConnectionStatu connectionStatu = new ConnectionStatu();
            connectionStatu.Code = code;
            return connectionStatu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.Int32 _Code;
        partial void OnCodeChanging(global::System.Int32 value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_ConfigModel", "FK_Connection_connectionState", "Connection")]
        public EntityCollection<Connection> Connections
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Connection>("TZero_ConfigModel.FK_Connection_connectionState", "Connection");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Connection>("TZero_ConfigModel.FK_Connection_connectionState", "Connection", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TZero_ConfigModel", Name="Module")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Module : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Module object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Module CreateModule(global::System.Int32 code, global::System.String name)
        {
            Module module = new Module();
            module.Code = code;
            module.Name = name;
            return module;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.Int32 _Code;
        partial void OnCodeChanging(global::System.Int32 value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Active;
        partial void OnActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_ConfigModel", "Terminal_Module", "Terminal")]
        public EntityCollection<Terminal> Terminals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Terminal>("TZero_ConfigModel.Terminal_Module", "Terminal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Terminal>("TZero_ConfigModel.Terminal_Module", "Terminal", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TZero_ConfigModel", Name="SystemProperty")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SystemProperty : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SystemProperty object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        public static SystemProperty CreateSystemProperty(global::System.String code)
        {
            SystemProperty systemProperty = new SystemProperty();
            systemProperty.Code = code;
            return systemProperty;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TZero_ConfigModel", Name="Terminal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Terminal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Terminal object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        public static Terminal CreateTerminal(global::System.Int32 code, global::System.String name, global::System.Boolean active)
        {
            Terminal terminal = new Terminal();
            terminal.Code = code;
            terminal.Name = name;
            terminal.Active = active;
            return terminal;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.Int32 _Code;
        partial void OnCodeChanging(global::System.Int32 value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastSync
        {
            get
            {
                return _LastSync;
            }
            set
            {
                OnLastSyncChanging(value);
                ReportPropertyChanging("LastSync");
                _LastSync = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastSync");
                OnLastSyncChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastSync;
        partial void OnLastSyncChanging(Nullable<global::System.DateTime> value);
        partial void OnLastSyncChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsSyncronized
        {
            get
            {
                return _IsSyncronized;
            }
            set
            {
                OnIsSyncronizedChanging(value);
                ReportPropertyChanging("IsSyncronized");
                _IsSyncronized = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSyncronized");
                OnIsSyncronizedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsSyncronized;
        partial void OnIsSyncronizedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSyncronizedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_ConfigModel", "FK_Connection_Terminal", "Connection")]
        public EntityCollection<Connection> Connections
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Connection>("TZero_ConfigModel.FK_Connection_Terminal", "Connection");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Connection>("TZero_ConfigModel.FK_Connection_Terminal", "Connection", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_ConfigModel", "FK_TerminalProperty_Terminal", "TerminalProperty")]
        public EntityCollection<TerminalProperty> TerminalProperties
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TerminalProperty>("TZero_ConfigModel.FK_TerminalProperty_Terminal", "TerminalProperty");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TerminalProperty>("TZero_ConfigModel.FK_TerminalProperty_Terminal", "TerminalProperty", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_ConfigModel", "Terminal_Module", "Module")]
        public EntityCollection<Module> Modules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Module>("TZero_ConfigModel.Terminal_Module", "Module");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Module>("TZero_ConfigModel.Terminal_Module", "Module", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TZero_ConfigModel", Name="TerminalProperty")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TerminalProperty : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TerminalProperty object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="terminalCode">Initial value of the TerminalCode property.</param>
        public static TerminalProperty CreateTerminalProperty(global::System.String code, global::System.Int32 terminalCode)
        {
            TerminalProperty terminalProperty = new TerminalProperty();
            terminalProperty.Code = code;
            terminalProperty.TerminalCode = terminalCode;
            return terminalProperty;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TerminalCode
        {
            get
            {
                return _TerminalCode;
            }
            set
            {
                if (_TerminalCode != value)
                {
                    OnTerminalCodeChanging(value);
                    ReportPropertyChanging("TerminalCode");
                    _TerminalCode = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TerminalCode");
                    OnTerminalCodeChanged();
                }
            }
        }
        private global::System.Int32 _TerminalCode;
        partial void OnTerminalCodeChanging(global::System.Int32 value);
        partial void OnTerminalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LargeValue
        {
            get
            {
                return _LargeValue;
            }
            set
            {
                OnLargeValueChanging(value);
                ReportPropertyChanging("LargeValue");
                _LargeValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LargeValue");
                OnLargeValueChanged();
            }
        }
        private global::System.String _LargeValue;
        partial void OnLargeValueChanging(global::System.String value);
        partial void OnLargeValueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_ConfigModel", "FK_TerminalProperty_Terminal", "Terminal")]
        public Terminal Terminal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Terminal>("TZero_ConfigModel.FK_TerminalProperty_Terminal", "Terminal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Terminal>("TZero_ConfigModel.FK_TerminalProperty_Terminal", "Terminal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Terminal> TerminalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Terminal>("TZero_ConfigModel.FK_TerminalProperty_Terminal", "Terminal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Terminal>("TZero_ConfigModel.FK_TerminalProperty_Terminal", "Terminal", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
