//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace TerminalZeroWebClient.ServiceHelperReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VirtualLogEntry", Namespace="http://schemas.datacontract.org/2004/07/ZeroLogHandle.Classes")]
    public partial class VirtualLogEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IndentLevelField;
        
        private string MessageField;
        
        private System.DateTime StampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IndentLevel {
            get {
                return this.IndentLevelField;
            }
            set {
                if ((this.IndentLevelField.Equals(value) != true)) {
                    this.IndentLevelField = value;
                    this.RaisePropertyChanged("IndentLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Stamp {
            get {
                return this.StampField;
            }
            set {
                if ((this.StampField.Equals(value) != true)) {
                    this.StampField = value;
                    this.RaisePropertyChanged("Stamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pack", Namespace="http://schemas.datacontract.org/2004/07/ZeroCommonClasses.Entities", IsReference=true)]
    public partial class Pack : TerminalZeroWebClient.ServiceHelperReference.EntityObject {
        
        private int CodeField;
        
        private TerminalZeroWebClient.ServiceHelperReference.Connection ConnectionField;
        
        private string ConnectionCodeField;
        
        private TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfConnectionAMTtCmoD ConnectionReferenceField;
        
        private byte[] DataField;
        
        private bool EnableField;
        
        private System.Nullable<bool> IsMasterDataField;
        
        private System.Nullable<bool> IsUpgradeField;
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.PackPending> PackPendingsField;
        
        private TerminalZeroWebClient.ServiceHelperReference.PackStatu PackStatuField;
        
        private TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfPackStatuAMTtCmoD PackStatuReferenceField;
        
        private System.Nullable<int> PackStatusCodeField;
        
        private string ResultField;
        
        private System.Nullable<System.DateTime> StampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.Connection Connection {
            get {
                return this.ConnectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionField, value) != true)) {
                    this.ConnectionField = value;
                    this.RaisePropertyChanged("Connection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnectionCode {
            get {
                return this.ConnectionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionCodeField, value) != true)) {
                    this.ConnectionCodeField = value;
                    this.RaisePropertyChanged("ConnectionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfConnectionAMTtCmoD ConnectionReference {
            get {
                return this.ConnectionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionReferenceField, value) != true)) {
                    this.ConnectionReferenceField = value;
                    this.RaisePropertyChanged("ConnectionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enable {
            get {
                return this.EnableField;
            }
            set {
                if ((this.EnableField.Equals(value) != true)) {
                    this.EnableField = value;
                    this.RaisePropertyChanged("Enable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsMasterData {
            get {
                return this.IsMasterDataField;
            }
            set {
                if ((this.IsMasterDataField.Equals(value) != true)) {
                    this.IsMasterDataField = value;
                    this.RaisePropertyChanged("IsMasterData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsUpgrade {
            get {
                return this.IsUpgradeField;
            }
            set {
                if ((this.IsUpgradeField.Equals(value) != true)) {
                    this.IsUpgradeField = value;
                    this.RaisePropertyChanged("IsUpgrade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.PackPending> PackPendings {
            get {
                return this.PackPendingsField;
            }
            set {
                if ((object.ReferenceEquals(this.PackPendingsField, value) != true)) {
                    this.PackPendingsField = value;
                    this.RaisePropertyChanged("PackPendings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.PackStatu PackStatu {
            get {
                return this.PackStatuField;
            }
            set {
                if ((object.ReferenceEquals(this.PackStatuField, value) != true)) {
                    this.PackStatuField = value;
                    this.RaisePropertyChanged("PackStatu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfPackStatuAMTtCmoD PackStatuReference {
            get {
                return this.PackStatuReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.PackStatuReferenceField, value) != true)) {
                    this.PackStatuReferenceField = value;
                    this.RaisePropertyChanged("PackStatuReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PackStatusCode {
            get {
                return this.PackStatusCodeField;
            }
            set {
                if ((this.PackStatusCodeField.Equals(value) != true)) {
                    this.PackStatusCodeField = value;
                    this.RaisePropertyChanged("PackStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Stamp {
            get {
                return this.StampField;
            }
            set {
                if ((this.StampField.Equals(value) != true)) {
                    this.StampField = value;
                    this.RaisePropertyChanged("Stamp");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Connection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.PackPending))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.PackStatu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Terminal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Connection1))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.ConnectionStatu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Module))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.TerminalProperty))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Pack))]
    public partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Connection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.PackPending))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.PackStatu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Terminal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Connection1))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.ConnectionStatu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Module))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.TerminalProperty))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Pack))]
    public partial class EntityObject : TerminalZeroWebClient.ServiceHelperReference.StructuralObject {
        
        private TerminalZeroWebClient.ServiceHelperReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Connection", Namespace="http://schemas.datacontract.org/2004/07/ZeroCommonClasses.Entities", IsReference=true)]
    public partial class Connection : TerminalZeroWebClient.ServiceHelperReference.EntityObject {
        
        private string CodeField;
        
        private System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack> PacksField;
        
        private System.DateTime StampField;
        
        private System.Nullable<int> StatusCodeField;
        
        private int TerminalCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack> Packs {
            get {
                return this.PacksField;
            }
            set {
                if ((object.ReferenceEquals(this.PacksField, value) != true)) {
                    this.PacksField = value;
                    this.RaisePropertyChanged("Packs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Stamp {
            get {
                return this.StampField;
            }
            set {
                if ((this.StampField.Equals(value) != true)) {
                    this.StampField = value;
                    this.RaisePropertyChanged("Stamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TerminalCode {
            get {
                return this.TerminalCodeField;
            }
            set {
                if ((this.TerminalCodeField.Equals(value) != true)) {
                    this.TerminalCodeField = value;
                    this.RaisePropertyChanged("TerminalCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PackPending", Namespace="http://schemas.datacontract.org/2004/07/ZeroCommonClasses.Entities", IsReference=true)]
    public partial class PackPending : TerminalZeroWebClient.ServiceHelperReference.EntityObject {
        
        private TerminalZeroWebClient.ServiceHelperReference.Pack PackField;
        
        private int PackCodeField;
        
        private TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfPackAMTtCmoD PackReferenceField;
        
        private System.Nullable<System.DateTime> StampField;
        
        private int TerminalCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.Pack Pack {
            get {
                return this.PackField;
            }
            set {
                if ((object.ReferenceEquals(this.PackField, value) != true)) {
                    this.PackField = value;
                    this.RaisePropertyChanged("Pack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PackCode {
            get {
                return this.PackCodeField;
            }
            set {
                if ((this.PackCodeField.Equals(value) != true)) {
                    this.PackCodeField = value;
                    this.RaisePropertyChanged("PackCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfPackAMTtCmoD PackReference {
            get {
                return this.PackReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.PackReferenceField, value) != true)) {
                    this.PackReferenceField = value;
                    this.RaisePropertyChanged("PackReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Stamp {
            get {
                return this.StampField;
            }
            set {
                if ((this.StampField.Equals(value) != true)) {
                    this.StampField = value;
                    this.RaisePropertyChanged("Stamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TerminalCode {
            get {
                return this.TerminalCodeField;
            }
            set {
                if ((this.TerminalCodeField.Equals(value) != true)) {
                    this.TerminalCodeField = value;
                    this.RaisePropertyChanged("TerminalCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PackStatu", Namespace="http://schemas.datacontract.org/2004/07/ZeroCommonClasses.Entities", IsReference=true)]
    public partial class PackStatu : TerminalZeroWebClient.ServiceHelperReference.EntityObject {
        
        private int CodeField;
        
        private string DescriptionField;
        
        private System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack> PacksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack> Packs {
            get {
                return this.PacksField;
            }
            set {
                if ((object.ReferenceEquals(this.PacksField, value) != true)) {
                    this.PacksField = value;
                    this.RaisePropertyChanged("Packs");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Terminal", Namespace="http://schemas.datacontract.org/2004/07/ZeroConfiguration.Entities", IsReference=true)]
    public partial class Terminal : TerminalZeroWebClient.ServiceHelperReference.EntityObject {
        
        private bool ActiveField;
        
        private int CodeField;
        
        private System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Connection1> ConnectionsField;
        
        private string DescriptionField;
        
        private System.Nullable<bool> IsSyncronizedField;
        
        private System.Nullable<System.DateTime> LastSyncField;
        
        private System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Module> ModulesField;
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.TerminalProperty> TerminalPropertiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Connection1> Connections {
            get {
                return this.ConnectionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionsField, value) != true)) {
                    this.ConnectionsField = value;
                    this.RaisePropertyChanged("Connections");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsSyncronized {
            get {
                return this.IsSyncronizedField;
            }
            set {
                if ((this.IsSyncronizedField.Equals(value) != true)) {
                    this.IsSyncronizedField = value;
                    this.RaisePropertyChanged("IsSyncronized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastSync {
            get {
                return this.LastSyncField;
            }
            set {
                if ((this.LastSyncField.Equals(value) != true)) {
                    this.LastSyncField = value;
                    this.RaisePropertyChanged("LastSync");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Module> Modules {
            get {
                return this.ModulesField;
            }
            set {
                if ((object.ReferenceEquals(this.ModulesField, value) != true)) {
                    this.ModulesField = value;
                    this.RaisePropertyChanged("Modules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.TerminalProperty> TerminalProperties {
            get {
                return this.TerminalPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalPropertiesField, value) != true)) {
                    this.TerminalPropertiesField = value;
                    this.RaisePropertyChanged("TerminalProperties");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Connection", Namespace="http://schemas.datacontract.org/2004/07/ZeroConfiguration.Entities", IsReference=true)]
    public partial class Connection1 : TerminalZeroWebClient.ServiceHelperReference.EntityObject {
        
        private string CodeField;
        
        private TerminalZeroWebClient.ServiceHelperReference.ConnectionStatu ConnectionStatuField;
        
        private TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfConnectionStatunM6hmTEN ConnectionStatuReferenceField;
        
        private System.DateTime StampField;
        
        private System.Nullable<int> StatusCodeField;
        
        private TerminalZeroWebClient.ServiceHelperReference.Terminal TerminalField;
        
        private int TerminalCodeField;
        
        private TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfTerminalnM6hmTEN TerminalReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.ConnectionStatu ConnectionStatu {
            get {
                return this.ConnectionStatuField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionStatuField, value) != true)) {
                    this.ConnectionStatuField = value;
                    this.RaisePropertyChanged("ConnectionStatu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfConnectionStatunM6hmTEN ConnectionStatuReference {
            get {
                return this.ConnectionStatuReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionStatuReferenceField, value) != true)) {
                    this.ConnectionStatuReferenceField = value;
                    this.RaisePropertyChanged("ConnectionStatuReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Stamp {
            get {
                return this.StampField;
            }
            set {
                if ((this.StampField.Equals(value) != true)) {
                    this.StampField = value;
                    this.RaisePropertyChanged("Stamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.Terminal Terminal {
            get {
                return this.TerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalField, value) != true)) {
                    this.TerminalField = value;
                    this.RaisePropertyChanged("Terminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TerminalCode {
            get {
                return this.TerminalCodeField;
            }
            set {
                if ((this.TerminalCodeField.Equals(value) != true)) {
                    this.TerminalCodeField = value;
                    this.RaisePropertyChanged("TerminalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfTerminalnM6hmTEN TerminalReference {
            get {
                return this.TerminalReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalReferenceField, value) != true)) {
                    this.TerminalReferenceField = value;
                    this.RaisePropertyChanged("TerminalReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionStatu", Namespace="http://schemas.datacontract.org/2004/07/ZeroConfiguration.Entities", IsReference=true)]
    public partial class ConnectionStatu : TerminalZeroWebClient.ServiceHelperReference.EntityObject {
        
        private int CodeField;
        
        private System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Connection1> ConnectionsField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Connection1> Connections {
            get {
                return this.ConnectionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionsField, value) != true)) {
                    this.ConnectionsField = value;
                    this.RaisePropertyChanged("Connections");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Module", Namespace="http://schemas.datacontract.org/2004/07/ZeroConfiguration.Entities", IsReference=true)]
    public partial class Module : TerminalZeroWebClient.ServiceHelperReference.EntityObject {
        
        private System.Nullable<bool> ActiveField;
        
        private int CodeField;
        
        private string DescriptionField;
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Terminal> TerminalsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Terminal> Terminals {
            get {
                return this.TerminalsField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalsField, value) != true)) {
                    this.TerminalsField = value;
                    this.RaisePropertyChanged("Terminals");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TerminalProperty", Namespace="http://schemas.datacontract.org/2004/07/ZeroConfiguration.Entities", IsReference=true)]
    public partial class TerminalProperty : TerminalZeroWebClient.ServiceHelperReference.EntityObject {
        
        private string CodeField;
        
        private string DescriptionField;
        
        private string LargeValueField;
        
        private TerminalZeroWebClient.ServiceHelperReference.Terminal TerminalField;
        
        private int TerminalCodeField;
        
        private TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfTerminalnM6hmTEN TerminalReferenceField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LargeValue {
            get {
                return this.LargeValueField;
            }
            set {
                if ((object.ReferenceEquals(this.LargeValueField, value) != true)) {
                    this.LargeValueField = value;
                    this.RaisePropertyChanged("LargeValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.Terminal Terminal {
            get {
                return this.TerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalField, value) != true)) {
                    this.TerminalField = value;
                    this.RaisePropertyChanged("Terminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TerminalCode {
            get {
                return this.TerminalCodeField;
            }
            set {
                if ((this.TerminalCodeField.Equals(value) != true)) {
                    this.TerminalCodeField = value;
                    this.RaisePropertyChanged("TerminalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfTerminalnM6hmTEN TerminalReference {
            get {
                return this.TerminalReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalReferenceField, value) != true)) {
                    this.TerminalReferenceField = value;
                    this.RaisePropertyChanged("TerminalReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EntityContainerNameField;
        
        private System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.EntityKeyMember> EntityKeyValuesField;
        
        private string EntitySetNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.EntityKeyMember> EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfConnectionAMTtCmoD", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfConnectionAMTtCmoD : TerminalZeroWebClient.ServiceHelperReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfPackStatuAMTtCmoD", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfPackStatuAMTtCmoD : TerminalZeroWebClient.ServiceHelperReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.EntityKeyMember>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.VirtualLogEntry>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.VirtualLogEntry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Pack))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Connection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.PackPending>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.PackPending))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.PackStatu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.ZeroResponseOfArrayOfTerminalnM6hmTEN))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfConnectionAMTtCmoD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfPackAMTtCmoD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfPackStatuAMTtCmoD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfConnectionStatunM6hmTEN))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfTerminalnM6hmTEN))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Terminal>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Terminal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Connection1>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Connection1))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.ConnectionStatu))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Module>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.Module))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.TerminalProperty>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.TerminalProperty))]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string KeyField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZeroResponseOfArrayOfTerminalnM6hmTEN", Namespace="http://schemas.datacontract.org/2004/07/ZeroCommonClasses.GlobalObjects")]
    public partial class ZeroResponseOfArrayOfTerminalnM6hmTEN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool IsValidField;
        
        private string MessageField;
        
        private System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Terminal> ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Terminal> Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfConnectionAMTtCmoD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfPackStatuAMTtCmoD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfConnectionStatunM6hmTEN))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfTerminalnM6hmTEN))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfPackAMTtCmoD))]
    public partial class EntityReference : TerminalZeroWebClient.ServiceHelperReference.RelatedEnd {
        
        private TerminalZeroWebClient.ServiceHelperReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TerminalZeroWebClient.ServiceHelperReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfConnectionAMTtCmoD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfPackStatuAMTtCmoD))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfConnectionStatunM6hmTEN))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfTerminalnM6hmTEN))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TerminalZeroWebClient.ServiceHelperReference.EntityReferenceOfPackAMTtCmoD))]
    public partial class RelatedEnd : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfPackAMTtCmoD", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfPackAMTtCmoD : TerminalZeroWebClient.ServiceHelperReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfConnectionStatunM6hmTEN", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfConnectionStatunM6hmTEN : TerminalZeroWebClient.ServiceHelperReference.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfTerminalnM6hmTEN", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfTerminalnM6hmTEN : TerminalZeroWebClient.ServiceHelperReference.EntityReference {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceHelperReference.ServiceHelper")]
    public interface ServiceHelper {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServiceHelper/GetLogsStr", ReplyAction="http://tempuri.org/ServiceHelper/GetLogsStrResponse")]
        System.IAsyncResult BeginGetLogsStr(System.DateTime lastStamp, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndGetLogsStr(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServiceHelper/GetLogs", ReplyAction="http://tempuri.org/ServiceHelper/GetLogsResponse")]
        System.IAsyncResult BeginGetLogs(System.DateTime lastStamp, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.VirtualLogEntry> EndGetLogs(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServiceHelper/GetPack", ReplyAction="http://tempuri.org/ServiceHelper/GetPackResponse")]
        System.IAsyncResult BeginGetPack(System.DateTime startDate, System.DateTime endDate, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack> EndGetPack(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServiceHelper/GetTerminalsStatus", ReplyAction="http://tempuri.org/ServiceHelper/GetTerminalsStatusResponse")]
        System.IAsyncResult BeginGetTerminalsStatus(System.AsyncCallback callback, object asyncState);
        
        TerminalZeroWebClient.ServiceHelperReference.ZeroResponseOfArrayOfTerminalnM6hmTEN EndGetTerminalsStatus(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceHelperChannel : TerminalZeroWebClient.ServiceHelperReference.ServiceHelper, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLogsStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLogsStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLogsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLogsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.VirtualLogEntry> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.VirtualLogEntry>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTerminalsStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTerminalsStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TerminalZeroWebClient.ServiceHelperReference.ZeroResponseOfArrayOfTerminalnM6hmTEN Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TerminalZeroWebClient.ServiceHelperReference.ZeroResponseOfArrayOfTerminalnM6hmTEN)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHelperClient : System.ServiceModel.ClientBase<TerminalZeroWebClient.ServiceHelperReference.ServiceHelper>, TerminalZeroWebClient.ServiceHelperReference.ServiceHelper {
        
        private BeginOperationDelegate onBeginGetLogsStrDelegate;
        
        private EndOperationDelegate onEndGetLogsStrDelegate;
        
        private System.Threading.SendOrPostCallback onGetLogsStrCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLogsDelegate;
        
        private EndOperationDelegate onEndGetLogsDelegate;
        
        private System.Threading.SendOrPostCallback onGetLogsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPackDelegate;
        
        private EndOperationDelegate onEndGetPackDelegate;
        
        private System.Threading.SendOrPostCallback onGetPackCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTerminalsStatusDelegate;
        
        private EndOperationDelegate onEndGetTerminalsStatusDelegate;
        
        private System.Threading.SendOrPostCallback onGetTerminalsStatusCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServiceHelperClient() {
        }
        
        public ServiceHelperClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHelperClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHelperClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHelperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetLogsStrCompletedEventArgs> GetLogsStrCompleted;
        
        public event System.EventHandler<GetLogsCompletedEventArgs> GetLogsCompleted;
        
        public event System.EventHandler<GetPackCompletedEventArgs> GetPackCompleted;
        
        public event System.EventHandler<GetTerminalsStatusCompletedEventArgs> GetTerminalsStatusCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TerminalZeroWebClient.ServiceHelperReference.ServiceHelper.BeginGetLogsStr(System.DateTime lastStamp, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLogsStr(lastStamp, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> TerminalZeroWebClient.ServiceHelperReference.ServiceHelper.EndGetLogsStr(System.IAsyncResult result) {
            return base.Channel.EndGetLogsStr(result);
        }
        
        private System.IAsyncResult OnBeginGetLogsStr(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.DateTime lastStamp = ((System.DateTime)(inValues[0]));
            return ((TerminalZeroWebClient.ServiceHelperReference.ServiceHelper)(this)).BeginGetLogsStr(lastStamp, callback, asyncState);
        }
        
        private object[] OnEndGetLogsStr(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((TerminalZeroWebClient.ServiceHelperReference.ServiceHelper)(this)).EndGetLogsStr(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLogsStrCompleted(object state) {
            if ((this.GetLogsStrCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLogsStrCompleted(this, new GetLogsStrCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLogsStrAsync(System.DateTime lastStamp) {
            this.GetLogsStrAsync(lastStamp, null);
        }
        
        public void GetLogsStrAsync(System.DateTime lastStamp, object userState) {
            if ((this.onBeginGetLogsStrDelegate == null)) {
                this.onBeginGetLogsStrDelegate = new BeginOperationDelegate(this.OnBeginGetLogsStr);
            }
            if ((this.onEndGetLogsStrDelegate == null)) {
                this.onEndGetLogsStrDelegate = new EndOperationDelegate(this.OnEndGetLogsStr);
            }
            if ((this.onGetLogsStrCompletedDelegate == null)) {
                this.onGetLogsStrCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLogsStrCompleted);
            }
            base.InvokeAsync(this.onBeginGetLogsStrDelegate, new object[] {
                        lastStamp}, this.onEndGetLogsStrDelegate, this.onGetLogsStrCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TerminalZeroWebClient.ServiceHelperReference.ServiceHelper.BeginGetLogs(System.DateTime lastStamp, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLogs(lastStamp, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.VirtualLogEntry> TerminalZeroWebClient.ServiceHelperReference.ServiceHelper.EndGetLogs(System.IAsyncResult result) {
            return base.Channel.EndGetLogs(result);
        }
        
        private System.IAsyncResult OnBeginGetLogs(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.DateTime lastStamp = ((System.DateTime)(inValues[0]));
            return ((TerminalZeroWebClient.ServiceHelperReference.ServiceHelper)(this)).BeginGetLogs(lastStamp, callback, asyncState);
        }
        
        private object[] OnEndGetLogs(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.VirtualLogEntry> retVal = ((TerminalZeroWebClient.ServiceHelperReference.ServiceHelper)(this)).EndGetLogs(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLogsCompleted(object state) {
            if ((this.GetLogsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLogsCompleted(this, new GetLogsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLogsAsync(System.DateTime lastStamp) {
            this.GetLogsAsync(lastStamp, null);
        }
        
        public void GetLogsAsync(System.DateTime lastStamp, object userState) {
            if ((this.onBeginGetLogsDelegate == null)) {
                this.onBeginGetLogsDelegate = new BeginOperationDelegate(this.OnBeginGetLogs);
            }
            if ((this.onEndGetLogsDelegate == null)) {
                this.onEndGetLogsDelegate = new EndOperationDelegate(this.OnEndGetLogs);
            }
            if ((this.onGetLogsCompletedDelegate == null)) {
                this.onGetLogsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLogsCompleted);
            }
            base.InvokeAsync(this.onBeginGetLogsDelegate, new object[] {
                        lastStamp}, this.onEndGetLogsDelegate, this.onGetLogsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TerminalZeroWebClient.ServiceHelperReference.ServiceHelper.BeginGetPack(System.DateTime startDate, System.DateTime endDate, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPack(startDate, endDate, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack> TerminalZeroWebClient.ServiceHelperReference.ServiceHelper.EndGetPack(System.IAsyncResult result) {
            return base.Channel.EndGetPack(result);
        }
        
        private System.IAsyncResult OnBeginGetPack(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.DateTime startDate = ((System.DateTime)(inValues[0]));
            System.DateTime endDate = ((System.DateTime)(inValues[1]));
            return ((TerminalZeroWebClient.ServiceHelperReference.ServiceHelper)(this)).BeginGetPack(startDate, endDate, callback, asyncState);
        }
        
        private object[] OnEndGetPack(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack> retVal = ((TerminalZeroWebClient.ServiceHelperReference.ServiceHelper)(this)).EndGetPack(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPackCompleted(object state) {
            if ((this.GetPackCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPackCompleted(this, new GetPackCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPackAsync(System.DateTime startDate, System.DateTime endDate) {
            this.GetPackAsync(startDate, endDate, null);
        }
        
        public void GetPackAsync(System.DateTime startDate, System.DateTime endDate, object userState) {
            if ((this.onBeginGetPackDelegate == null)) {
                this.onBeginGetPackDelegate = new BeginOperationDelegate(this.OnBeginGetPack);
            }
            if ((this.onEndGetPackDelegate == null)) {
                this.onEndGetPackDelegate = new EndOperationDelegate(this.OnEndGetPack);
            }
            if ((this.onGetPackCompletedDelegate == null)) {
                this.onGetPackCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPackCompleted);
            }
            base.InvokeAsync(this.onBeginGetPackDelegate, new object[] {
                        startDate,
                        endDate}, this.onEndGetPackDelegate, this.onGetPackCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TerminalZeroWebClient.ServiceHelperReference.ServiceHelper.BeginGetTerminalsStatus(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTerminalsStatus(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TerminalZeroWebClient.ServiceHelperReference.ZeroResponseOfArrayOfTerminalnM6hmTEN TerminalZeroWebClient.ServiceHelperReference.ServiceHelper.EndGetTerminalsStatus(System.IAsyncResult result) {
            return base.Channel.EndGetTerminalsStatus(result);
        }
        
        private System.IAsyncResult OnBeginGetTerminalsStatus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((TerminalZeroWebClient.ServiceHelperReference.ServiceHelper)(this)).BeginGetTerminalsStatus(callback, asyncState);
        }
        
        private object[] OnEndGetTerminalsStatus(System.IAsyncResult result) {
            TerminalZeroWebClient.ServiceHelperReference.ZeroResponseOfArrayOfTerminalnM6hmTEN retVal = ((TerminalZeroWebClient.ServiceHelperReference.ServiceHelper)(this)).EndGetTerminalsStatus(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTerminalsStatusCompleted(object state) {
            if ((this.GetTerminalsStatusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTerminalsStatusCompleted(this, new GetTerminalsStatusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTerminalsStatusAsync() {
            this.GetTerminalsStatusAsync(null);
        }
        
        public void GetTerminalsStatusAsync(object userState) {
            if ((this.onBeginGetTerminalsStatusDelegate == null)) {
                this.onBeginGetTerminalsStatusDelegate = new BeginOperationDelegate(this.OnBeginGetTerminalsStatus);
            }
            if ((this.onEndGetTerminalsStatusDelegate == null)) {
                this.onEndGetTerminalsStatusDelegate = new EndOperationDelegate(this.OnEndGetTerminalsStatus);
            }
            if ((this.onGetTerminalsStatusCompletedDelegate == null)) {
                this.onGetTerminalsStatusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTerminalsStatusCompleted);
            }
            base.InvokeAsync(this.onBeginGetTerminalsStatusDelegate, null, this.onEndGetTerminalsStatusDelegate, this.onGetTerminalsStatusCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TerminalZeroWebClient.ServiceHelperReference.ServiceHelper CreateChannel() {
            return new ServiceHelperClientChannel(this);
        }
        
        private class ServiceHelperClientChannel : ChannelBase<TerminalZeroWebClient.ServiceHelperReference.ServiceHelper>, TerminalZeroWebClient.ServiceHelperReference.ServiceHelper {
            
            public ServiceHelperClientChannel(System.ServiceModel.ClientBase<TerminalZeroWebClient.ServiceHelperReference.ServiceHelper> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetLogsStr(System.DateTime lastStamp, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = lastStamp;
                System.IAsyncResult _result = base.BeginInvoke("GetLogsStr", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndGetLogsStr(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("GetLogsStr", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLogs(System.DateTime lastStamp, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = lastStamp;
                System.IAsyncResult _result = base.BeginInvoke("GetLogs", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.VirtualLogEntry> EndGetLogs(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.VirtualLogEntry> _result = ((System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.VirtualLogEntry>)(base.EndInvoke("GetLogs", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPack(System.DateTime startDate, System.DateTime endDate, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = startDate;
                _args[1] = endDate;
                System.IAsyncResult _result = base.BeginInvoke("GetPack", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack> EndGetPack(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack> _result = ((System.Collections.ObjectModel.ObservableCollection<TerminalZeroWebClient.ServiceHelperReference.Pack>)(base.EndInvoke("GetPack", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTerminalsStatus(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTerminalsStatus", _args, callback, asyncState);
                return _result;
            }
            
            public TerminalZeroWebClient.ServiceHelperReference.ZeroResponseOfArrayOfTerminalnM6hmTEN EndGetTerminalsStatus(System.IAsyncResult result) {
                object[] _args = new object[0];
                TerminalZeroWebClient.ServiceHelperReference.ZeroResponseOfArrayOfTerminalnM6hmTEN _result = ((TerminalZeroWebClient.ServiceHelperReference.ZeroResponseOfArrayOfTerminalnM6hmTEN)(base.EndInvoke("GetTerminalsStatus", _args, result)));
                return _result;
            }
        }
    }
}
