//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroConfiguration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroConfiguration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido realizar la acción deseada.
        /// </summary>
        internal static string CannotExecuteAction {
            get {
                return ResourceManager.GetString("CannotExecuteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conexión no fue inicializada.
        /// </summary>
        internal static string ConnectionFinished {
            get {
                return ResourceManager.GetString("ConnectionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comuniquese con el Administrador del sistema.
        /// </summary>
        internal static string ContactSystemAdministrator {
            get {
                return ResourceManager.GetString("ContactSystemAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///La Terminal fue desactivada para realizar esta acción..
        /// </summary>
        internal static string DeactivatedTerminal {
            get {
                return ResourceManager.GetString("DeactivatedTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de terminal inválido, mínimo 4 caracteres.
        /// </summary>
        internal static string InvalidTerminalName {
            get {
                return ResourceManager.GetString("InvalidTerminalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se excedió el número máximo de terminales.
        /// </summary>
        internal static string MaxTerminalsReach {
            get {
                return ResourceManager.GetString("MaxTerminalsReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La conexión ha superado el tiempo de espera máximo.
        /// </summary>
        internal static string MaxTimeReach {
            get {
                return ResourceManager.GetString("MaxTimeReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario/password incorrectos. Por favor intente nuevamente!.
        /// </summary>
        internal static string MsgIncorrectUserPassTryAgain {
            get {
                return ResourceManager.GetString("MsgIncorrectUserPassTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor ingrese su usuario!.
        /// </summary>
        internal static string MsgLogInPlease {
            get {
                return ResourceManager.GetString("MsgLogInPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal nueva, se intentará crearla.
        /// </summary>
        internal static string NewTerminal {
            get {
                return ResourceManager.GetString("NewTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronizando cada {0} minutos.
        /// </summary>
        internal static string SyncEveryFormat {
            get {
                return ResourceManager.GetString("SyncEveryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha asignado el parámetro.
        /// </summary>
        internal static string UnasignedParameter {
            get {
                return ResourceManager.GetString("UnasignedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta Terminal no esta autorizada para realizar esta acción!.
        /// </summary>
        internal static string UnauthorizedTrminal {
            get {
                return ResourceManager.GetString("UnauthorizedTrminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No esta autorizado para realizar esta acción!.
        /// </summary>
        internal static string UnauthorizedUser {
            get {
                return ResourceManager.GetString("UnauthorizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe la regla con el nombre &apos;{0}&apos;
        ///.
        /// </summary>
        internal static string UnexistentRuleNamed_ {
            get {
                return ResourceManager.GetString("UnexistentRuleNamed?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error inesperado en la ejecución.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal válida.
        /// </summary>
        internal static string ValidTerminal {
            get {
                return ResourceManager.GetString("ValidTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario válido.
        /// </summary>
        internal static string ValidUser {
            get {
                return ResourceManager.GetString("ValidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre no concuerda con el existente en la central..
        /// </summary>
        internal static string WrongTerminalName {
            get {
                return ResourceManager.GetString("WrongTerminalName", resourceCulture);
            }
        }
    }
}
