//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TZero_CommonModel", "FK_ConnectionCode_Pack_Connection", "Connection", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ZeroCommonClasses.Entities.Connection), "Pack", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ZeroCommonClasses.Entities.Pack), true)]
[assembly: EdmRelationshipAttribute("TZero_CommonModel", "FK_PackStatusCode_Pack_PackStatus", "PackStatu", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ZeroCommonClasses.Entities.PackStatu), "Pack", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ZeroCommonClasses.Entities.Pack), true)]
[assembly: EdmRelationshipAttribute("TZero_CommonModel", "FK_PackPending_Pack", "Pack", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ZeroCommonClasses.Entities.Pack), "PackPending", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ZeroCommonClasses.Entities.PackPending), true)]

#endregion

namespace ZeroCommonClasses.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PackStatu> PackStatus
        {
            get
            {
                if ((_PackStatus == null))
                {
                    _PackStatus = base.CreateObjectSet<PackStatu>("PackStatus");
                }
                return _PackStatus;
            }
        }
        private ObjectSet<PackStatu> _PackStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Connection> Connections
        {
            get
            {
                if ((_Connections == null))
                {
                    _Connections = base.CreateObjectSet<Connection>("Connections");
                }
                return _Connections;
            }
        }
        private ObjectSet<Connection> _Connections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pack> Packs
        {
            get
            {
                if ((_Packs == null))
                {
                    _Packs = base.CreateObjectSet<Pack>("Packs");
                }
                return _Packs;
            }
        }
        private ObjectSet<Pack> _Packs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PackPending> PackPendings
        {
            get
            {
                if ((_PackPendings == null))
                {
                    _PackPendings = base.CreateObjectSet<PackPending>("PackPendings");
                }
                return _PackPendings;
            }
        }
        private ObjectSet<PackPending> _PackPendings;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PackStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPackStatus(PackStatu packStatu)
        {
            base.AddObject("PackStatus", packStatu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Connections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConnections(Connection connection)
        {
            base.AddObject("Connections", connection);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Packs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPacks(Pack pack)
        {
            base.AddObject("Packs", pack);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PackPendings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPackPendings(PackPending packPending)
        {
            base.AddObject("PackPendings", packPending);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="terminalCode">No Metadata Documentation available.</param>
        public ObjectResult<PackToSend> GetPacksToSend(Nullable<global::System.Int32> terminalCode)
        {
            ObjectParameter terminalCodeParameter;
            if (terminalCode.HasValue)
            {
                terminalCodeParameter = new ObjectParameter("TerminalCode", terminalCode);
            }
            else
            {
                terminalCodeParameter = new ObjectParameter("TerminalCode", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<PackToSend>("GetPacksToSend", terminalCodeParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TZero_CommonModel", Name="Connection")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Connection : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Connection object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="terminalCode">Initial value of the TerminalCode property.</param>
        /// <param name="stamp">Initial value of the Stamp property.</param>
        public static Connection CreateConnection(global::System.String code, global::System.Int32 terminalCode, global::System.DateTime stamp)
        {
            Connection connection = new Connection();
            connection.Code = code;
            connection.TerminalCode = terminalCode;
            connection.Stamp = stamp;
            return connection;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TerminalCode
        {
            get
            {
                return _TerminalCode;
            }
            set
            {
                OnTerminalCodeChanging(value);
                ReportPropertyChanging("TerminalCode");
                _TerminalCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TerminalCode");
                OnTerminalCodeChanged();
            }
        }
        private global::System.Int32 _TerminalCode;
        partial void OnTerminalCodeChanging(global::System.Int32 value);
        partial void OnTerminalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Stamp
        {
            get
            {
                return _Stamp;
            }
            set
            {
                OnStampChanging(value);
                ReportPropertyChanging("Stamp");
                _Stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stamp");
                OnStampChanged();
            }
        }
        private global::System.DateTime _Stamp;
        partial void OnStampChanging(global::System.DateTime value);
        partial void OnStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StatusCode
        {
            get
            {
                return _StatusCode;
            }
            set
            {
                OnStatusCodeChanging(value);
                ReportPropertyChanging("StatusCode");
                _StatusCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusCode");
                OnStatusCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _StatusCode;
        partial void OnStatusCodeChanging(Nullable<global::System.Int32> value);
        partial void OnStatusCodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_CommonModel", "FK_ConnectionCode_Pack_Connection", "Pack")]
        public EntityCollection<Pack> Packs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pack>("TZero_CommonModel.FK_ConnectionCode_Pack_Connection", "Pack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pack>("TZero_CommonModel.FK_ConnectionCode_Pack_Connection", "Pack", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TZero_CommonModel", Name="Pack")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pack : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pack object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="enable">Initial value of the Enable property.</param>
        public static Pack CreatePack(global::System.Int32 code, global::System.Boolean enable)
        {
            Pack pack = new Pack();
            pack.Code = code;
            pack.Enable = enable;
            return pack;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.Int32 _Code;
        partial void OnCodeChanging(global::System.Int32 value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Stamp
        {
            get
            {
                return _Stamp;
            }
            set
            {
                OnStampChanging(value);
                ReportPropertyChanging("Stamp");
                _Stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stamp");
                OnStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _Stamp;
        partial void OnStampChanging(Nullable<global::System.DateTime> value);
        partial void OnStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Enable
        {
            get
            {
                return _Enable;
            }
            set
            {
                OnEnableChanging(value);
                ReportPropertyChanging("Enable");
                _Enable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Enable");
                OnEnableChanged();
            }
        }
        private global::System.Boolean _Enable;
        partial void OnEnableChanging(global::System.Boolean value);
        partial void OnEnableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Data
        {
            get
            {
                return StructuralObject.GetValidValue(_Data);
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.Byte[] _Data;
        partial void OnDataChanging(global::System.Byte[] value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PackStatusCode
        {
            get
            {
                return _PackStatusCode;
            }
            set
            {
                OnPackStatusCodeChanging(value);
                ReportPropertyChanging("PackStatusCode");
                _PackStatusCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PackStatusCode");
                OnPackStatusCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _PackStatusCode;
        partial void OnPackStatusCodeChanging(Nullable<global::System.Int32> value);
        partial void OnPackStatusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ConnectionCode
        {
            get
            {
                return _ConnectionCode;
            }
            set
            {
                OnConnectionCodeChanging(value);
                ReportPropertyChanging("ConnectionCode");
                _ConnectionCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ConnectionCode");
                OnConnectionCodeChanged();
            }
        }
        private global::System.String _ConnectionCode;
        partial void OnConnectionCodeChanging(global::System.String value);
        partial void OnConnectionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Result
        {
            get
            {
                return _Result;
            }
            set
            {
                OnResultChanging(value);
                ReportPropertyChanging("Result");
                _Result = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Result");
                OnResultChanged();
            }
        }
        private global::System.String _Result;
        partial void OnResultChanging(global::System.String value);
        partial void OnResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsMasterData
        {
            get
            {
                return _IsMasterData;
            }
            set
            {
                OnIsMasterDataChanging(value);
                ReportPropertyChanging("IsMasterData");
                _IsMasterData = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMasterData");
                OnIsMasterDataChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsMasterData;
        partial void OnIsMasterDataChanging(Nullable<global::System.Boolean> value);
        partial void OnIsMasterDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsUpgrade
        {
            get
            {
                return _IsUpgrade;
            }
            set
            {
                OnIsUpgradeChanging(value);
                ReportPropertyChanging("IsUpgrade");
                _IsUpgrade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsUpgrade");
                OnIsUpgradeChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsUpgrade;
        partial void OnIsUpgradeChanging(Nullable<global::System.Boolean> value);
        partial void OnIsUpgradeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_CommonModel", "FK_ConnectionCode_Pack_Connection", "Connection")]
        public Connection Connection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Connection>("TZero_CommonModel.FK_ConnectionCode_Pack_Connection", "Connection").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Connection>("TZero_CommonModel.FK_ConnectionCode_Pack_Connection", "Connection").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Connection> ConnectionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Connection>("TZero_CommonModel.FK_ConnectionCode_Pack_Connection", "Connection");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Connection>("TZero_CommonModel.FK_ConnectionCode_Pack_Connection", "Connection", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_CommonModel", "FK_PackStatusCode_Pack_PackStatus", "PackStatu")]
        public PackStatu PackStatu
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PackStatu>("TZero_CommonModel.FK_PackStatusCode_Pack_PackStatus", "PackStatu").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PackStatu>("TZero_CommonModel.FK_PackStatusCode_Pack_PackStatus", "PackStatu").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PackStatu> PackStatuReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PackStatu>("TZero_CommonModel.FK_PackStatusCode_Pack_PackStatus", "PackStatu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PackStatu>("TZero_CommonModel.FK_PackStatusCode_Pack_PackStatus", "PackStatu", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_CommonModel", "FK_PackPending_Pack", "PackPending")]
        public EntityCollection<PackPending> PackPendings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PackPending>("TZero_CommonModel.FK_PackPending_Pack", "PackPending");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PackPending>("TZero_CommonModel.FK_PackPending_Pack", "PackPending", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TZero_CommonModel", Name="PackPending")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PackPending : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PackPending object.
        /// </summary>
        /// <param name="packCode">Initial value of the PackCode property.</param>
        /// <param name="terminalCode">Initial value of the TerminalCode property.</param>
        public static PackPending CreatePackPending(global::System.Int32 packCode, global::System.Int32 terminalCode)
        {
            PackPending packPending = new PackPending();
            packPending.PackCode = packCode;
            packPending.TerminalCode = terminalCode;
            return packPending;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PackCode
        {
            get
            {
                return _PackCode;
            }
            set
            {
                if (_PackCode != value)
                {
                    OnPackCodeChanging(value);
                    ReportPropertyChanging("PackCode");
                    _PackCode = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PackCode");
                    OnPackCodeChanged();
                }
            }
        }
        private global::System.Int32 _PackCode;
        partial void OnPackCodeChanging(global::System.Int32 value);
        partial void OnPackCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TerminalCode
        {
            get
            {
                return _TerminalCode;
            }
            set
            {
                if (_TerminalCode != value)
                {
                    OnTerminalCodeChanging(value);
                    ReportPropertyChanging("TerminalCode");
                    _TerminalCode = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TerminalCode");
                    OnTerminalCodeChanged();
                }
            }
        }
        private global::System.Int32 _TerminalCode;
        partial void OnTerminalCodeChanging(global::System.Int32 value);
        partial void OnTerminalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Stamp
        {
            get
            {
                return _Stamp;
            }
            set
            {
                OnStampChanging(value);
                ReportPropertyChanging("Stamp");
                _Stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stamp");
                OnStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _Stamp;
        partial void OnStampChanging(Nullable<global::System.DateTime> value);
        partial void OnStampChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_CommonModel", "FK_PackPending_Pack", "Pack")]
        public Pack Pack
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pack>("TZero_CommonModel.FK_PackPending_Pack", "Pack").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pack>("TZero_CommonModel.FK_PackPending_Pack", "Pack").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pack> PackReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pack>("TZero_CommonModel.FK_PackPending_Pack", "Pack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pack>("TZero_CommonModel.FK_PackPending_Pack", "Pack", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TZero_CommonModel", Name="PackStatu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PackStatu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PackStatu object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        public static PackStatu CreatePackStatu(global::System.Int32 code)
        {
            PackStatu packStatu = new PackStatu();
            packStatu.Code = code;
            return packStatu;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.Int32 _Code;
        partial void OnCodeChanging(global::System.Int32 value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TZero_CommonModel", "FK_PackStatusCode_Pack_PackStatus", "Pack")]
        public EntityCollection<Pack> Packs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pack>("TZero_CommonModel.FK_PackStatusCode_Pack_PackStatus", "Pack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pack>("TZero_CommonModel.FK_PackStatusCode_Pack_PackStatus", "Pack", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TZero_CommonModel", Name="PackToSend")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class PackToSend : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PackToSend object.
        /// </summary>
        /// <param name="packCode">Initial value of the PackCode property.</param>
        /// <param name="packName">Initial value of the PackName property.</param>
        public static PackToSend CreatePackToSend(global::System.Int32 packCode, global::System.String packName)
        {
            PackToSend packToSend = new PackToSend();
            packToSend.PackCode = packCode;
            packToSend.PackName = packName;
            return packToSend;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PackCode
        {
            get
            {
                return _PackCode;
            }
            set
            {
                OnPackCodeChanging(value);
                ReportPropertyChanging("PackCode");
                _PackCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PackCode");
                OnPackCodeChanged();
            }
        }
        private global::System.Int32 _PackCode;
        partial void OnPackCodeChanging(global::System.Int32 value);
        partial void OnPackCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PackName
        {
            get
            {
                return _PackName;
            }
            set
            {
                OnPackNameChanging(value);
                ReportPropertyChanging("PackName");
                _PackName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PackName");
                OnPackNameChanged();
            }
        }
        private global::System.String _PackName;
        partial void OnPackNameChanging(global::System.String value);
        partial void OnPackNameChanged();

        #endregion
    }

    #endregion
    
}
